name: Cross-Build

on:
  push:
    branches:
      - edgewize
      - master
      - 2.*
  pull_request:
    branches:
      - edgewize
      - master
      - 2.*

jobs:
  cross-build-test:
    strategy:
      fail-fast: false
      matrix:
        goos:
          - 'linux'
        go:
          - '1.21'

        include:
          # Set the minimum Go patch version for the given Go minor
          # Usable via ${{ matrix.GO_SEMVER }}
          - go: '1.21'
            GO_SEMVER: '~1.21.0'

    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.GO_SEMVER }}
          check-latest: true

      - name: Print Go version and environment
        id: vars
        run: |
          printf "Using go at: $(which go)\n"
          printf "Go version: $(go version)\n"
          printf "\n\nGo environment:\n\n"
          go env
          printf "\n\nSystem environment:\n\n"
          env

      - name: Log into registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin ${{ vars.IMAGE_REPO }}

      - name: Declare some variables
        shell: bash
        run: |
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
          echo "suffix=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Run Build
        run: |
          docker build -f Dockerfile . --push --tag ${{ vars.IMAGE_REPO }}/edgewize/caddy:${{ env.branch }}-${{ env.suffix }}
